import React, { useMemo, useState, useEffect, useRef, useCallback } from "react";
import { View, Text, StyleSheet, Pressable, ScrollView, Animated, Image, Platform, Alert, Linking, Dimensions } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useRouter, useLocalSearchParams } from "expo-router";
import * as Haptics from "expo-haptics";
import { useThemeColors } from "@/providers/ThemeProvider";
import { ThemeColors } from "@/constants/colors";
import { useAuth } from "@/providers/AuthProvider";
import { communityStore, StoredCommunity } from "@/lib/communityStore";
import { recordCommunityEngagement } from "@/hooks/useReviewPrompt";
import { AutoScrollView } from "@/components/AutoScrollView";
import { createCpStyles } from "./community.cp.styles";
